name: Project Proposal
description: Suggest an idea for a project
labels: []

body:
  - type: textarea
    attributes:
      label: Description
      description: one or two paragraphs describing the idea. Projects should take approximately 3 months to reasonably complete. The projects will 1) build technical skills, increase our number of core contributors, and work on meaningful projects we want to integrate into Qiskit or maintain; 2) Tackle problems that relate to advancing quantum computing. For example, publishing a quantum computing paper, building a successful local community, or increasing diversity.
    validations:
      required: true

  - type: markdown
    attributes:
      values: \# Mentors

  - type: input
    attributes:
      label: Mentor/s names
      description: Are you able to mentor this project?
    validations:
      required: true

  - type: input
    attributes:
      label: Mentor/s GitHub IDs
      description: Please enter mentor/s GitHub ID/s with '@'. Seperate with ',' for more than one mentor. (e.g. `@HuangJunye, @javabster`)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Number of mentees
      description: What is the ideal number of people to work on this project?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
    validations:
      required: true

  - type: textarea
    attributes:
      label: Type of mentees
      description: What are the profiles of the ideal participants for this idea?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Deliverable
      description: What's the expected result?
    validations:
      required: true